### ISSUE TITLE
emmet with jade not working ,output html not jade

### ISSUE THREAD

**Issue by jeodiong** [sergeche/emmet-sublime#581] opened 2015-10-28 01:57 UTC
![image](http://7vztjt.com1.z0.glb.clouddn.com/Screen%20Shot%202015-10-28%20at%2009.54.08.png)

**Comment by cekerholic** [comment] 2015-10-28 05:10
Same issue here. Found out that the problem is not on Emmet itself but from [jade plugin](https://github.com/davidrios/jade-tmbundle/), specifically from this commit https://github.com/davidrios/jade-tmbundle/commit/b11cfd850985060a8d992c3359bedbc55e14fb82. Reverting jade to https://github.com/davidrios/jade-tmbundle/commit/fea35b58dca320d1d7940948162b7fd3fa9a1b1d resolving the problem for me.

**Comment by cekerholic** [comment] 2015-10-28 05:13
BTW, you have to remove jade from package control first. Then clone the repo to your Sublime `Packages` directory (not `Installed Packages`)

**Comment by xiansheng** [comment] 2015-10-28 06:17
not working for me

**Comment by cekerholic** [comment] 2015-10-28 08:19
@xiansheng hmm weird, mine worked perfectly. I use emmet from package control and jade from  davidrios/jade-tmbundle@fea35b5. Are you sure you're placing the jade repo in the right directory? (in my machine it's `~/.config/sublime-text-3/Packages`)

**Comment by xiansheng** [comment] 2015-10-28 15:14
yes it's worked! thank you very much.

**Comment by jeodiong** [comment] 2015-10-29 01:42
mine still not working

**Comment by cekerholic** [comment] 2015-10-29 05:07
@jeodiong  please review your Package Control settings ( `Preferences -> Package Settings -> Package Controls -> Settings - User`) and make sure jade plugin is already removed. Then open `Packages` directory from `Preferences -> Browse Packages...`, clone [davidrios/jade-tmbundle](https://github.com/davidrios/jade-tmbundle) there and then checkout to davidrios/jade-tmbundle@fea35b5 (`git checkout fea35b5`).

I've only tested in my Linux machine, what OS do you use?

**Comment by jeodiong** [comment] 2015-10-29 12:46
@cekerholic mac os and it is working , thank you very much.

**Comment by sergeche** [comment] 2015-10-29 15:50
Just pushed update, hope it helps

**Comment by sergeche** [comment] 2015-10-29 15:50
Should work with most recent Jade package

**Comment by jeodiong** [comment] 2015-10-29 16:10
@sergeche  thank you

**Closed** 2015-10-30 01:23 UTC
